spring:
  application:
    name: ORDER-SERVICE
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 9091

eureka:
  client:
    register-with-eureka: ture
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: localhost